version: '3.3'

services:
  db:
    image: mongo:4.4
  ports:
    - 27017:27017
  volumes:
    - db-data:/data/db
    - mongo-config:/data/configdb

  fetch-service:
    build:
      dockerfile: ./fetch-service/Dockerfile
    ports:
      - "5000:5000"
    restart: always

    database-service:
      build:
        dockerfile: ./database-service/Dockerfile
      ports:
        - "5000:5000"
      restart: always

      transform-service:
        build:
          dockerfile: ./transform-service/Dockerfile
        ports:
          - "5000:5000"
        restart: always
