version: '3.3'

services:
  db:
    image: couchdb:3.1.1
  ports:
    - 2894:2894
  volumes:
    - db-data:/opt/couchdb/data

  fetch-service:
    build:
      dockerfile: ./fetch-service/Dockerfile
    ports:
      - "5000:5000"
    restart: always

  database-service:
    build:
      dockerfile: ./database-service/Dockerfile
    ports:
      - "5000:5000"
    restart: always