apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: berlin-covid-prediction
spec:
  schedule: "0 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: script
            image: registry.datexis.com/kbrendel/berlin_intensivecare_prediction:latest                                  
          imagePullSecrets: 
            - name: private-registry-auth
          restartPolicy: Never
