apiVersion: v1
kind: Service
metadata:
  name: couchdb-nodeport
  namespace: sachs
spec:
  type: NodePort
  ports:
  - nodePort: 31111
    port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    statefulset.kubernetes.io/pod-name: couchdb-0
