---
apiVersion: v1
kind: Service
metadata:
  name: couch-service
  namespace: sachs
  labels:
    app: couch
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5984
    protocol: TCP
    targetPort: 5984
  selector:
    app: couch         # label selector
