apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couch-pvc-couchdb-0
  namespace: sachs
  labels:
    volume: couch-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couch-pvc-couchdb-1
  namespace: sachs
  labels:
    volume: couch-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couch-pvc-couchdb-2
  namespace: sachs
  labels:
    volume: couch-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
